using System.Runtime.CompilerServices;

[assembly:TypeForwardedTo (typeof (AndroidX.Lifecycle.AndroidViewModel))]
[assembly:TypeForwardedTo (typeof (AndroidX.Lifecycle.IHasDefaultViewModelProviderFactory))]
[assembly:TypeForwardedTo (typeof (AndroidX.Lifecycle.IViewModelStoreOwner))]
[assembly:TypeForwardedTo (typeof (AndroidX.Lifecycle.ViewModel))]
[assembly:TypeForwardedTo (typeof (AndroidX.Lifecycle.ViewModelLazy))]
[assembly:TypeForwardedTo (typeof (AndroidX.Lifecycle.ViewModelProvider))]
[assembly:TypeForwardedTo (typeof (AndroidX.Lifecycle.ViewModelProviderGetKt))]
[assembly:TypeForwardedTo (typeof (AndroidX.Lifecycle.ViewModelStore))]
[assembly:TypeForwardedTo (typeof (AndroidX.Lifecycle.ViewTreeViewModelKt))]
[assembly:TypeForwardedTo (typeof (AndroidX.Lifecycle.ViewTreeViewModelStoreOwner))]
[assembly:TypeForwardedTo (typeof (AndroidX.Lifecycle.ViewModels.CreationExtras))]
[assembly:TypeForwardedTo (typeof (AndroidX.Lifecycle.ViewModels.InitializerViewModelFactoryBuilder))]
[assembly:TypeForwardedTo (typeof (AndroidX.Lifecycle.ViewModels.InitializerViewModelFactoryKt))]
[assembly:TypeForwardedTo (typeof (AndroidX.Lifecycle.ViewModels.IViewModelFactoryDsl))]
[assembly:TypeForwardedTo (typeof (AndroidX.Lifecycle.ViewModels.MutableCreationExtras))]
[assembly:TypeForwardedTo (typeof (AndroidX.Lifecycle.ViewModels.ViewModelFactoryDslAttribute))]
[assembly:TypeForwardedTo (typeof (AndroidX.Lifecycle.ViewModels.ViewModelInitializer))]
