//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable restore
using System;
using System.Collections.Generic;
using Android.Runtime;
using Java.Interop;

namespace Google.Android.Material.SideSheet {

	// Metadata.xml XPath class reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']"
	[global::Android.Runtime.Register ("com/google/android/material/sidesheet/SideSheetBehavior", DoNotGenerateAcw=true)]
	[global::Java.Interop.JavaTypeParameters (new string [] {"V extends android.view.View"})]
	public partial class SideSheetBehavior : global::AndroidX.CoordinatorLayout.Widget.CoordinatorLayout.Behavior {
		public static class InterfaceConsts {
			// The following are fields from: com.google.android.material.sidesheet.Sheet

			// Metadata.xml XPath field reference: path="/api/package[@name='com.google.android.material.sidesheet']/interface[@name='Sheet']/field[@name='EDGE_RIGHT']"
			[Register ("EDGE_RIGHT")]
			public const int EdgeRight = (int) 0;

			// Metadata.xml XPath field reference: path="/api/package[@name='com.google.android.material.sidesheet']/interface[@name='Sheet']/field[@name='STATE_DRAGGING']"
			[Register ("STATE_DRAGGING")]
			public const int StateDragging = (int) 1;

			// Metadata.xml XPath field reference: path="/api/package[@name='com.google.android.material.sidesheet']/interface[@name='Sheet']/field[@name='STATE_EXPANDED']"
			[Register ("STATE_EXPANDED")]
			public const int StateExpanded = (int) 3;

			// Metadata.xml XPath field reference: path="/api/package[@name='com.google.android.material.sidesheet']/interface[@name='Sheet']/field[@name='STATE_HIDDEN']"
			[Register ("STATE_HIDDEN")]
			public const int StateHidden = (int) 5;

			// Metadata.xml XPath field reference: path="/api/package[@name='com.google.android.material.sidesheet']/interface[@name='Sheet']/field[@name='STATE_SETTLING']"
			[Register ("STATE_SETTLING")]
			public const int StateSettling = (int) 2;

		}

		// Metadata.xml XPath class reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior.SavedState']"
		[global::Android.Runtime.Register ("com/google/android/material/sidesheet/SideSheetBehavior$SavedState", DoNotGenerateAcw=true)]
		protected internal partial class SavedState : global::AndroidX.CustomView.View.AbsSavedState {

			// Metadata.xml XPath field reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior.SavedState']/field[@name='CREATOR']"
			[Register ("CREATOR")]
			public static global::Android.OS.IParcelableCreator? Creator {
				get {
					const string __id = "CREATOR.Landroid/os/Parcelable$Creator;";

					var __v = _members.StaticFields.GetObjectValue (__id);
					return global::Java.Lang.Object.GetObject<global::Android.OS.IParcelableCreator> (__v.Handle, JniHandleOwnership.TransferLocalRef);
				}
			}

			static readonly JniPeerMembers _members = new XAPeerMembers ("com/google/android/material/sidesheet/SideSheetBehavior$SavedState", typeof (SavedState));

			internal static IntPtr class_ref {
				get { return _members.JniPeerType.PeerReference.Handle; }
			}

			[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
			[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
			public override global::Java.Interop.JniPeerMembers JniPeerMembers {
				get { return _members; }
			}

			[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
			[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
			protected override IntPtr ThresholdClass {
				get { return _members.JniPeerType.PeerReference.Handle; }
			}

			[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
			[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
			protected override global::System.Type ThresholdType {
				get { return _members.ManagedPeerType; }
			}

			protected SavedState (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
			{
			}

			// Metadata.xml XPath constructor reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior.SavedState']/constructor[@name='SideSheetBehavior.SavedState' and count(parameter)=1 and parameter[1][@type='android.os.Parcel']]"
			[Register (".ctor", "(Landroid/os/Parcel;)V", "")]
			public unsafe SavedState (global::Android.OS.Parcel source) : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
			{
				const string __id = "(Landroid/os/Parcel;)V";

				if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
					return;

				try {
					JniArgumentValue* __args = stackalloc JniArgumentValue [1];
					__args [0] = new JniArgumentValue ((source == null) ? IntPtr.Zero : ((global::Java.Lang.Object) source).Handle);
					var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
					SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
					_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
				} finally {
					global::System.GC.KeepAlive (source);
				}
			}

			// Metadata.xml XPath constructor reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior.SavedState']/constructor[@name='SideSheetBehavior.SavedState' and count(parameter)=2 and parameter[1][@type='android.os.Parcel'] and parameter[2][@type='java.lang.ClassLoader']]"
			[Register (".ctor", "(Landroid/os/Parcel;Ljava/lang/ClassLoader;)V", "")]
			public unsafe SavedState (global::Android.OS.Parcel source, global::Java.Lang.ClassLoader? loader) : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
			{
				const string __id = "(Landroid/os/Parcel;Ljava/lang/ClassLoader;)V";

				if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
					return;

				try {
					JniArgumentValue* __args = stackalloc JniArgumentValue [2];
					__args [0] = new JniArgumentValue ((source == null) ? IntPtr.Zero : ((global::Java.Lang.Object) source).Handle);
					__args [1] = new JniArgumentValue ((loader == null) ? IntPtr.Zero : ((global::Java.Lang.Object) loader).Handle);
					var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
					SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
					_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
				} finally {
					global::System.GC.KeepAlive (source);
					global::System.GC.KeepAlive (loader);
				}
			}

			// Metadata.xml XPath constructor reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior.SavedState']/constructor[@name='SideSheetBehavior.SavedState' and count(parameter)=2 and parameter[1][@type='android.os.Parcelable'] and parameter[2][@type='com.google.android.material.sidesheet.SideSheetBehavior&lt;?&gt;']]"
			[Register (".ctor", "(Landroid/os/Parcelable;Lcom/google/android/material/sidesheet/SideSheetBehavior;)V", "")]
			public unsafe SavedState (global::Android.OS.IParcelable? superState, global::Google.Android.Material.SideSheet.SideSheetBehavior behavior) : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
			{
				const string __id = "(Landroid/os/Parcelable;Lcom/google/android/material/sidesheet/SideSheetBehavior;)V";

				if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
					return;

				try {
					JniArgumentValue* __args = stackalloc JniArgumentValue [2];
					__args [0] = new JniArgumentValue ((superState == null) ? IntPtr.Zero : ((global::Java.Lang.Object) superState).Handle);
					__args [1] = new JniArgumentValue ((behavior == null) ? IntPtr.Zero : ((global::Java.Lang.Object) behavior).Handle);
					var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
					SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
					_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
				} finally {
					global::System.GC.KeepAlive (superState);
					global::System.GC.KeepAlive (behavior);
				}
			}

		}

		static readonly JniPeerMembers _members = new XAPeerMembers ("com/google/android/material/sidesheet/SideSheetBehavior", typeof (SideSheetBehavior));

		internal static IntPtr class_ref {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		public override global::Java.Interop.JniPeerMembers JniPeerMembers {
			get { return _members; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override IntPtr ThresholdClass {
			get { return _members.JniPeerType.PeerReference.Handle; }
		}

		[global::System.Diagnostics.DebuggerBrowsable (global::System.Diagnostics.DebuggerBrowsableState.Never)]
		[global::System.ComponentModel.EditorBrowsable (global::System.ComponentModel.EditorBrowsableState.Never)]
		protected override global::System.Type ThresholdType {
			get { return _members.ManagedPeerType; }
		}

		protected SideSheetBehavior (IntPtr javaReference, JniHandleOwnership transfer) : base (javaReference, transfer)
		{
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/constructor[@name='SideSheetBehavior' and count(parameter)=0]"
		[Register (".ctor", "()V", "")]
		public unsafe SideSheetBehavior () : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
		{
			const string __id = "()V";

			if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
				return;

			try {
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), null);
				SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
				_members.InstanceMethods.FinishCreateInstance (__id, this, null);
			} finally {
			}
		}

		// Metadata.xml XPath constructor reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/constructor[@name='SideSheetBehavior' and count(parameter)=2 and parameter[1][@type='android.content.Context'] and parameter[2][@type='android.util.AttributeSet']]"
		[Register (".ctor", "(Landroid/content/Context;Landroid/util/AttributeSet;)V", "")]
		public unsafe SideSheetBehavior (global::Android.Content.Context context, global::Android.Util.IAttributeSet? attrs) : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
		{
			const string __id = "(Landroid/content/Context;Landroid/util/AttributeSet;)V";

			if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
				return;

			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [2];
				__args [0] = new JniArgumentValue ((context == null) ? IntPtr.Zero : ((global::Java.Lang.Object) context).Handle);
				__args [1] = new JniArgumentValue ((attrs == null) ? IntPtr.Zero : ((global::Java.Lang.Object) attrs).Handle);
				var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
				SetHandle (__r.Handle, JniHandleOwnership.TransferLocalRef);
				_members.InstanceMethods.FinishCreateInstance (__id, this, __args);
			} finally {
				global::System.GC.KeepAlive (context);
				global::System.GC.KeepAlive (attrs);
			}
		}

		static Delegate? cb_getCoplanarSiblingView;
#pragma warning disable 0169
		static Delegate GetGetCoplanarSiblingViewHandler ()
		{
			if (cb_getCoplanarSiblingView == null)
				cb_getCoplanarSiblingView = JNINativeWrapper.CreateDelegate (new _JniMarshal_PP_L (n_GetCoplanarSiblingView));
			return cb_getCoplanarSiblingView;
		}

		static IntPtr n_GetCoplanarSiblingView (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			return JNIEnv.ToLocalJniHandle (__this.CoplanarSiblingView);
		}
#pragma warning restore 0169

		static Delegate? cb_setCoplanarSiblingView_Landroid_view_View_;
#pragma warning disable 0169
		static Delegate GetSetCoplanarSiblingView_Landroid_view_View_Handler ()
		{
			if (cb_setCoplanarSiblingView_Landroid_view_View_ == null)
				cb_setCoplanarSiblingView_Landroid_view_View_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPL_V (n_SetCoplanarSiblingView_Landroid_view_View_));
			return cb_setCoplanarSiblingView_Landroid_view_View_;
		}

		static void n_SetCoplanarSiblingView_Landroid_view_View_ (IntPtr jnienv, IntPtr native__this, IntPtr native_coplanarSiblingView)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			var coplanarSiblingView = global::Java.Lang.Object.GetObject<global::Android.Views.View> (native_coplanarSiblingView, JniHandleOwnership.DoNotTransfer);
			__this.CoplanarSiblingView = coplanarSiblingView;
		}
#pragma warning restore 0169

		public virtual unsafe global::Android.Views.View? CoplanarSiblingView {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='getCoplanarSiblingView' and count(parameter)=0]"
			[Register ("getCoplanarSiblingView", "()Landroid/view/View;", "GetGetCoplanarSiblingViewHandler")]
			get {
				const string __id = "getCoplanarSiblingView.()Landroid/view/View;";
				try {
					var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, null);
					return global::Java.Lang.Object.GetObject<global::Android.Views.View> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
				}
			}
			// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='setCoplanarSiblingView' and count(parameter)=1 and parameter[1][@type='android.view.View']]"
			[Register ("setCoplanarSiblingView", "(Landroid/view/View;)V", "GetSetCoplanarSiblingView_Landroid_view_View_Handler")]
			set {
				const string __id = "setCoplanarSiblingView.(Landroid/view/View;)V";
				try {
					JniArgumentValue* __args = stackalloc JniArgumentValue [1];
					__args [0] = new JniArgumentValue ((value == null) ? IntPtr.Zero : ((global::Java.Lang.Object) value).Handle);
					_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, __args);
				} finally {
					global::System.GC.KeepAlive (value);
				}
			}
		}

		static Delegate? cb_isDraggable;
#pragma warning disable 0169
		static Delegate GetIsDraggableHandler ()
		{
			if (cb_isDraggable == null)
				cb_isDraggable = JNINativeWrapper.CreateDelegate (new _JniMarshal_PP_Z (n_IsDraggable));
			return cb_isDraggable;
		}

		static bool n_IsDraggable (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			return __this.Draggable;
		}
#pragma warning restore 0169

		static Delegate? cb_setDraggable_Z;
#pragma warning disable 0169
		static Delegate GetSetDraggable_ZHandler ()
		{
			if (cb_setDraggable_Z == null)
				cb_setDraggable_Z = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPZ_V (n_SetDraggable_Z));
			return cb_setDraggable_Z;
		}

		static void n_SetDraggable_Z (IntPtr jnienv, IntPtr native__this, bool draggable)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			__this.Draggable = draggable;
		}
#pragma warning restore 0169

		public virtual unsafe bool Draggable {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='isDraggable' and count(parameter)=0]"
			[Register ("isDraggable", "()Z", "GetIsDraggableHandler")]
			get {
				const string __id = "isDraggable.()Z";
				try {
					var __rm = _members.InstanceMethods.InvokeVirtualBooleanMethod (__id, this, null);
					return __rm;
				} finally {
				}
			}
			// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='setDraggable' and count(parameter)=1 and parameter[1][@type='boolean']]"
			[Register ("setDraggable", "(Z)V", "GetSetDraggable_ZHandler")]
			set {
				const string __id = "setDraggable.(Z)V";
				try {
					JniArgumentValue* __args = stackalloc JniArgumentValue [1];
					__args [0] = new JniArgumentValue (value);
					_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, __args);
				} finally {
				}
			}
		}

		static Delegate? cb_getExpandedOffset;
#pragma warning disable 0169
		static Delegate GetGetExpandedOffsetHandler ()
		{
			if (cb_getExpandedOffset == null)
				cb_getExpandedOffset = JNINativeWrapper.CreateDelegate (new _JniMarshal_PP_I (n_GetExpandedOffset));
			return cb_getExpandedOffset;
		}

		static int n_GetExpandedOffset (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			return __this.ExpandedOffset;
		}
#pragma warning restore 0169

		public virtual unsafe int ExpandedOffset {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='getExpandedOffset' and count(parameter)=0]"
			[Register ("getExpandedOffset", "()I", "GetGetExpandedOffsetHandler")]
			get {
				const string __id = "getExpandedOffset.()I";
				try {
					var __rm = _members.InstanceMethods.InvokeVirtualInt32Method (__id, this, null);
					return __rm;
				} finally {
				}
			}
		}

		static Delegate? cb_getHideFriction;
#pragma warning disable 0169
		static Delegate GetGetHideFrictionHandler ()
		{
			if (cb_getHideFriction == null)
				cb_getHideFriction = JNINativeWrapper.CreateDelegate (new _JniMarshal_PP_F (n_GetHideFriction));
			return cb_getHideFriction;
		}

		static float n_GetHideFriction (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			return __this.HideFriction;
		}
#pragma warning restore 0169

		static Delegate? cb_setHideFriction_F;
#pragma warning disable 0169
		static Delegate GetSetHideFriction_FHandler ()
		{
			if (cb_setHideFriction_F == null)
				cb_setHideFriction_F = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPF_V (n_SetHideFriction_F));
			return cb_setHideFriction_F;
		}

		static void n_SetHideFriction_F (IntPtr jnienv, IntPtr native__this, float hideFriction)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			__this.HideFriction = hideFriction;
		}
#pragma warning restore 0169

		public virtual unsafe float HideFriction {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='getHideFriction' and count(parameter)=0]"
			[Register ("getHideFriction", "()F", "GetGetHideFrictionHandler")]
			get {
				const string __id = "getHideFriction.()F";
				try {
					var __rm = _members.InstanceMethods.InvokeVirtualSingleMethod (__id, this, null);
					return __rm;
				} finally {
				}
			}
			// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='setHideFriction' and count(parameter)=1 and parameter[1][@type='float']]"
			[Register ("setHideFriction", "(F)V", "GetSetHideFriction_FHandler")]
			set {
				const string __id = "setHideFriction.(F)V";
				try {
					JniArgumentValue* __args = stackalloc JniArgumentValue [1];
					__args [0] = new JniArgumentValue (value);
					_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, __args);
				} finally {
				}
			}
		}

		static Delegate? cb_getLastStableState;
#pragma warning disable 0169
		static Delegate GetGetLastStableStateHandler ()
		{
			if (cb_getLastStableState == null)
				cb_getLastStableState = JNINativeWrapper.CreateDelegate (new _JniMarshal_PP_I (n_GetLastStableState));
			return cb_getLastStableState;
		}

		static int n_GetLastStableState (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			return __this.LastStableState;
		}
#pragma warning restore 0169

		public virtual unsafe int LastStableState {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='getLastStableState' and count(parameter)=0]"
			[Register ("getLastStableState", "()I", "GetGetLastStableStateHandler")]
			get {
				const string __id = "getLastStableState.()I";
				try {
					var __rm = _members.InstanceMethods.InvokeVirtualInt32Method (__id, this, null);
					return __rm;
				} finally {
				}
			}
		}

		static Delegate? cb_getState;
#pragma warning disable 0169
		static Delegate GetGetStateHandler ()
		{
			if (cb_getState == null)
				cb_getState = JNINativeWrapper.CreateDelegate (new _JniMarshal_PP_I (n_GetState));
			return cb_getState;
		}

		static int n_GetState (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			return __this.State;
		}
#pragma warning restore 0169

		static Delegate? cb_setState_I;
#pragma warning disable 0169
		static Delegate GetSetState_IHandler ()
		{
			if (cb_setState_I == null)
				cb_setState_I = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPI_V (n_SetState_I));
			return cb_setState_I;
		}

		static void n_SetState_I (IntPtr jnienv, IntPtr native__this, int state)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			__this.State = state;
		}
#pragma warning restore 0169

		public virtual unsafe int State {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='getState' and count(parameter)=0]"
			[Register ("getState", "()I", "GetGetStateHandler")]
			get {
				const string __id = "getState.()I";
				try {
					var __rm = _members.InstanceMethods.InvokeVirtualInt32Method (__id, this, null);
					return __rm;
				} finally {
				}
			}
			// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='setState' and count(parameter)=1 and parameter[1][@type='int']]"
			[Register ("setState", "(I)V", "GetSetState_IHandler")]
			set {
				const string __id = "setState.(I)V";
				try {
					JniArgumentValue* __args = stackalloc JniArgumentValue [1];
					__args [0] = new JniArgumentValue (value);
					_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, __args);
				} finally {
				}
			}
		}

		static Delegate? cb_expand;
#pragma warning disable 0169
		static Delegate GetExpandHandler ()
		{
			if (cb_expand == null)
				cb_expand = JNINativeWrapper.CreateDelegate (new _JniMarshal_PP_V (n_Expand));
			return cb_expand;
		}

		static void n_Expand (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			__this.Expand ();
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='expand' and count(parameter)=0]"
		[Register ("expand", "()V", "GetExpandHandler")]
		public virtual unsafe void Expand ()
		{
			const string __id = "expand.()V";
			try {
				_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, null);
			} finally {
			}
		}

		// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='from' and count(parameter)=1 and parameter[1][@type='V']]"
		[Register ("from", "(Landroid/view/View;)Lcom/google/android/material/sidesheet/SideSheetBehavior;", "")]
		[global::Java.Interop.JavaTypeParameters (new string [] {"V extends android.view.View"})]
		public static unsafe global::Google.Android.Material.SideSheet.SideSheetBehavior From (global::Java.Lang.Object view)
		{
			const string __id = "from.(Landroid/view/View;)Lcom/google/android/material/sidesheet/SideSheetBehavior;";
			IntPtr native_view = JNIEnv.ToLocalJniHandle (view);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (native_view);
				var __rm = _members.StaticMethods.InvokeObjectMethod (__id, __args);
				return global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (__rm.Handle, JniHandleOwnership.TransferLocalRef)!;
			} finally {
				JNIEnv.DeleteLocalRef (native_view);
				global::System.GC.KeepAlive (view);
			}
		}

		static Delegate? cb_hide;
#pragma warning disable 0169
		static Delegate GetHideHandler ()
		{
			if (cb_hide == null)
				cb_hide = JNINativeWrapper.CreateDelegate (new _JniMarshal_PP_V (n_Hide));
			return cb_hide;
		}

		static void n_Hide (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			__this.Hide ();
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='hide' and count(parameter)=0]"
		[Register ("hide", "()V", "GetHideHandler")]
		public virtual unsafe void Hide ()
		{
			const string __id = "hide.()V";
			try {
				_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, null);
			} finally {
			}
		}

		static Delegate? cb_onInterceptTouchEvent_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_view_MotionEvent_;
#pragma warning disable 0169
		static Delegate GetOnInterceptTouchEvent_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_view_MotionEvent_Handler ()
		{
			if (cb_onInterceptTouchEvent_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_view_MotionEvent_ == null)
				cb_onInterceptTouchEvent_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_view_MotionEvent_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPLLL_Z (n_OnInterceptTouchEvent_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_view_MotionEvent_));
			return cb_onInterceptTouchEvent_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_view_MotionEvent_;
		}

		static bool n_OnInterceptTouchEvent_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_view_MotionEvent_ (IntPtr jnienv, IntPtr native__this, IntPtr native_parent, IntPtr native_child, IntPtr native_e)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			var parent = global::Java.Lang.Object.GetObject<global::AndroidX.CoordinatorLayout.Widget.CoordinatorLayout> (native_parent, JniHandleOwnership.DoNotTransfer);
			var child = global::Java.Lang.Object.GetObject<global::Java.Lang.Object> (native_child, JniHandleOwnership.DoNotTransfer);
			var e = global::Java.Lang.Object.GetObject<global::Android.Views.MotionEvent> (native_e, JniHandleOwnership.DoNotTransfer);
			bool __ret = __this.OnInterceptTouchEvent (parent!, child!, e!);
			return __ret;
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='onInterceptTouchEvent' and count(parameter)=3 and parameter[1][@type='androidx.coordinatorlayout.widget.CoordinatorLayout'] and parameter[2][@type='V'] and parameter[3][@type='android.view.MotionEvent']]"
		[Register ("onInterceptTouchEvent", "(Landroidx/coordinatorlayout/widget/CoordinatorLayout;Landroid/view/View;Landroid/view/MotionEvent;)Z", "GetOnInterceptTouchEvent_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_view_MotionEvent_Handler")]
		public override unsafe bool OnInterceptTouchEvent (global::AndroidX.CoordinatorLayout.Widget.CoordinatorLayout parent, global::Java.Lang.Object child, global::Android.Views.MotionEvent e)
		{
			const string __id = "onInterceptTouchEvent.(Landroidx/coordinatorlayout/widget/CoordinatorLayout;Landroid/view/View;Landroid/view/MotionEvent;)Z";
			IntPtr native_child = JNIEnv.ToLocalJniHandle (child);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [3];
				__args [0] = new JniArgumentValue ((parent == null) ? IntPtr.Zero : ((global::Java.Lang.Object) parent).Handle);
				__args [1] = new JniArgumentValue (native_child);
				__args [2] = new JniArgumentValue ((e == null) ? IntPtr.Zero : ((global::Java.Lang.Object) e).Handle);
				var __rm = _members.InstanceMethods.InvokeVirtualBooleanMethod (__id, this, __args);
				return __rm;
			} finally {
				JNIEnv.DeleteLocalRef (native_child);
				global::System.GC.KeepAlive (parent);
				global::System.GC.KeepAlive (child);
				global::System.GC.KeepAlive (e);
			}
		}

		static Delegate? cb_onLayoutChild_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_I;
#pragma warning disable 0169
		static Delegate GetOnLayoutChild_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_IHandler ()
		{
			if (cb_onLayoutChild_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_I == null)
				cb_onLayoutChild_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_I = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPLLI_Z (n_OnLayoutChild_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_I));
			return cb_onLayoutChild_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_I;
		}

		static bool n_OnLayoutChild_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_I (IntPtr jnienv, IntPtr native__this, IntPtr native_parent, IntPtr native_child, int layoutDirection)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			var parent = global::Java.Lang.Object.GetObject<global::AndroidX.CoordinatorLayout.Widget.CoordinatorLayout> (native_parent, JniHandleOwnership.DoNotTransfer);
			var child = global::Java.Lang.Object.GetObject<global::Java.Lang.Object> (native_child, JniHandleOwnership.DoNotTransfer);
			bool __ret = __this.OnLayoutChild (parent!, child!, layoutDirection);
			return __ret;
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='onLayoutChild' and count(parameter)=3 and parameter[1][@type='androidx.coordinatorlayout.widget.CoordinatorLayout'] and parameter[2][@type='V'] and parameter[3][@type='int']]"
		[Register ("onLayoutChild", "(Landroidx/coordinatorlayout/widget/CoordinatorLayout;Landroid/view/View;I)Z", "GetOnLayoutChild_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_IHandler")]
		public override unsafe bool OnLayoutChild (global::AndroidX.CoordinatorLayout.Widget.CoordinatorLayout parent, global::Java.Lang.Object child, int layoutDirection)
		{
			const string __id = "onLayoutChild.(Landroidx/coordinatorlayout/widget/CoordinatorLayout;Landroid/view/View;I)Z";
			IntPtr native_child = JNIEnv.ToLocalJniHandle (child);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [3];
				__args [0] = new JniArgumentValue ((parent == null) ? IntPtr.Zero : ((global::Java.Lang.Object) parent).Handle);
				__args [1] = new JniArgumentValue (native_child);
				__args [2] = new JniArgumentValue (layoutDirection);
				var __rm = _members.InstanceMethods.InvokeVirtualBooleanMethod (__id, this, __args);
				return __rm;
			} finally {
				JNIEnv.DeleteLocalRef (native_child);
				global::System.GC.KeepAlive (parent);
				global::System.GC.KeepAlive (child);
			}
		}

		static Delegate? cb_onMeasureChild_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_IIII;
#pragma warning disable 0169
		static Delegate GetOnMeasureChild_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_IIIIHandler ()
		{
			if (cb_onMeasureChild_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_IIII == null)
				cb_onMeasureChild_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_IIII = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPLLIIII_Z (n_OnMeasureChild_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_IIII));
			return cb_onMeasureChild_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_IIII;
		}

		static bool n_OnMeasureChild_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_IIII (IntPtr jnienv, IntPtr native__this, IntPtr native_parent, IntPtr native_child, int parentWidthMeasureSpec, int widthUsed, int parentHeightMeasureSpec, int heightUsed)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			var parent = global::Java.Lang.Object.GetObject<global::AndroidX.CoordinatorLayout.Widget.CoordinatorLayout> (native_parent, JniHandleOwnership.DoNotTransfer);
			var child = global::Java.Lang.Object.GetObject<global::Java.Lang.Object> (native_child, JniHandleOwnership.DoNotTransfer);
			bool __ret = __this.OnMeasureChild (parent!, child!, parentWidthMeasureSpec, widthUsed, parentHeightMeasureSpec, heightUsed);
			return __ret;
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='onMeasureChild' and count(parameter)=6 and parameter[1][@type='androidx.coordinatorlayout.widget.CoordinatorLayout'] and parameter[2][@type='V'] and parameter[3][@type='int'] and parameter[4][@type='int'] and parameter[5][@type='int'] and parameter[6][@type='int']]"
		[Register ("onMeasureChild", "(Landroidx/coordinatorlayout/widget/CoordinatorLayout;Landroid/view/View;IIII)Z", "GetOnMeasureChild_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_IIIIHandler")]
		public override unsafe bool OnMeasureChild (global::AndroidX.CoordinatorLayout.Widget.CoordinatorLayout parent, global::Java.Lang.Object child, int parentWidthMeasureSpec, int widthUsed, int parentHeightMeasureSpec, int heightUsed)
		{
			const string __id = "onMeasureChild.(Landroidx/coordinatorlayout/widget/CoordinatorLayout;Landroid/view/View;IIII)Z";
			IntPtr native_child = JNIEnv.ToLocalJniHandle (child);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [6];
				__args [0] = new JniArgumentValue ((parent == null) ? IntPtr.Zero : ((global::Java.Lang.Object) parent).Handle);
				__args [1] = new JniArgumentValue (native_child);
				__args [2] = new JniArgumentValue (parentWidthMeasureSpec);
				__args [3] = new JniArgumentValue (widthUsed);
				__args [4] = new JniArgumentValue (parentHeightMeasureSpec);
				__args [5] = new JniArgumentValue (heightUsed);
				var __rm = _members.InstanceMethods.InvokeVirtualBooleanMethod (__id, this, __args);
				return __rm;
			} finally {
				JNIEnv.DeleteLocalRef (native_child);
				global::System.GC.KeepAlive (parent);
				global::System.GC.KeepAlive (child);
			}
		}

		static Delegate? cb_onRestoreInstanceState_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_os_Parcelable_;
#pragma warning disable 0169
		static Delegate GetOnRestoreInstanceState_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_os_Parcelable_Handler ()
		{
			if (cb_onRestoreInstanceState_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_os_Parcelable_ == null)
				cb_onRestoreInstanceState_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_os_Parcelable_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPLLL_V (n_OnRestoreInstanceState_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_os_Parcelable_));
			return cb_onRestoreInstanceState_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_os_Parcelable_;
		}

		static void n_OnRestoreInstanceState_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_os_Parcelable_ (IntPtr jnienv, IntPtr native__this, IntPtr native_parent, IntPtr native_child, IntPtr native_state)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			var parent = global::Java.Lang.Object.GetObject<global::AndroidX.CoordinatorLayout.Widget.CoordinatorLayout> (native_parent, JniHandleOwnership.DoNotTransfer);
			var child = global::Java.Lang.Object.GetObject<global::Java.Lang.Object> (native_child, JniHandleOwnership.DoNotTransfer);
			var state = (global::Android.OS.IParcelable?)global::Java.Lang.Object.GetObject<global::Android.OS.IParcelable> (native_state, JniHandleOwnership.DoNotTransfer);
			__this.OnRestoreInstanceState (parent!, child!, state!);
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='onRestoreInstanceState' and count(parameter)=3 and parameter[1][@type='androidx.coordinatorlayout.widget.CoordinatorLayout'] and parameter[2][@type='V'] and parameter[3][@type='android.os.Parcelable']]"
		[Register ("onRestoreInstanceState", "(Landroidx/coordinatorlayout/widget/CoordinatorLayout;Landroid/view/View;Landroid/os/Parcelable;)V", "GetOnRestoreInstanceState_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_os_Parcelable_Handler")]
		public override unsafe void OnRestoreInstanceState (global::AndroidX.CoordinatorLayout.Widget.CoordinatorLayout parent, global::Java.Lang.Object child, global::Android.OS.IParcelable state)
		{
			const string __id = "onRestoreInstanceState.(Landroidx/coordinatorlayout/widget/CoordinatorLayout;Landroid/view/View;Landroid/os/Parcelable;)V";
			IntPtr native_child = JNIEnv.ToLocalJniHandle (child);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [3];
				__args [0] = new JniArgumentValue ((parent == null) ? IntPtr.Zero : ((global::Java.Lang.Object) parent).Handle);
				__args [1] = new JniArgumentValue (native_child);
				__args [2] = new JniArgumentValue ((state == null) ? IntPtr.Zero : ((global::Java.Lang.Object) state).Handle);
				_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, __args);
			} finally {
				JNIEnv.DeleteLocalRef (native_child);
				global::System.GC.KeepAlive (parent);
				global::System.GC.KeepAlive (child);
				global::System.GC.KeepAlive (state);
			}
		}

		static Delegate? cb_onSaveInstanceState_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_;
#pragma warning disable 0169
		static Delegate GetOnSaveInstanceState_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Handler ()
		{
			if (cb_onSaveInstanceState_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_ == null)
				cb_onSaveInstanceState_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPLL_L (n_OnSaveInstanceState_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_));
			return cb_onSaveInstanceState_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_;
		}

		static IntPtr n_OnSaveInstanceState_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_ (IntPtr jnienv, IntPtr native__this, IntPtr native_parent, IntPtr native_child)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			var parent = global::Java.Lang.Object.GetObject<global::AndroidX.CoordinatorLayout.Widget.CoordinatorLayout> (native_parent, JniHandleOwnership.DoNotTransfer);
			var child = global::Java.Lang.Object.GetObject<global::Java.Lang.Object> (native_child, JniHandleOwnership.DoNotTransfer);
			IntPtr __ret = JNIEnv.ToLocalJniHandle (__this.OnSaveInstanceState (parent!, child!));
			return __ret;
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='onSaveInstanceState' and count(parameter)=2 and parameter[1][@type='androidx.coordinatorlayout.widget.CoordinatorLayout'] and parameter[2][@type='V']]"
		[Register ("onSaveInstanceState", "(Landroidx/coordinatorlayout/widget/CoordinatorLayout;Landroid/view/View;)Landroid/os/Parcelable;", "GetOnSaveInstanceState_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Handler")]
		public override unsafe global::Android.OS.IParcelable OnSaveInstanceState (global::AndroidX.CoordinatorLayout.Widget.CoordinatorLayout parent, global::Java.Lang.Object child)
		{
			const string __id = "onSaveInstanceState.(Landroidx/coordinatorlayout/widget/CoordinatorLayout;Landroid/view/View;)Landroid/os/Parcelable;";
			IntPtr native_child = JNIEnv.ToLocalJniHandle (child);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [2];
				__args [0] = new JniArgumentValue ((parent == null) ? IntPtr.Zero : ((global::Java.Lang.Object) parent).Handle);
				__args [1] = new JniArgumentValue (native_child);
				var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, __args);
				return global::Java.Lang.Object.GetObject<global::Android.OS.IParcelable> (__rm.Handle, JniHandleOwnership.TransferLocalRef)!;
			} finally {
				JNIEnv.DeleteLocalRef (native_child);
				global::System.GC.KeepAlive (parent);
				global::System.GC.KeepAlive (child);
			}
		}

		static Delegate? cb_onTouchEvent_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_view_MotionEvent_;
#pragma warning disable 0169
		static Delegate GetOnTouchEvent_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_view_MotionEvent_Handler ()
		{
			if (cb_onTouchEvent_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_view_MotionEvent_ == null)
				cb_onTouchEvent_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_view_MotionEvent_ = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPLLL_Z (n_OnTouchEvent_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_view_MotionEvent_));
			return cb_onTouchEvent_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_view_MotionEvent_;
		}

		static bool n_OnTouchEvent_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_view_MotionEvent_ (IntPtr jnienv, IntPtr native__this, IntPtr native_parent, IntPtr native_child, IntPtr native_e)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			var parent = global::Java.Lang.Object.GetObject<global::AndroidX.CoordinatorLayout.Widget.CoordinatorLayout> (native_parent, JniHandleOwnership.DoNotTransfer);
			var child = global::Java.Lang.Object.GetObject<global::Java.Lang.Object> (native_child, JniHandleOwnership.DoNotTransfer);
			var e = global::Java.Lang.Object.GetObject<global::Android.Views.MotionEvent> (native_e, JniHandleOwnership.DoNotTransfer);
			bool __ret = __this.OnTouchEvent (parent!, child!, e!);
			return __ret;
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='onTouchEvent' and count(parameter)=3 and parameter[1][@type='androidx.coordinatorlayout.widget.CoordinatorLayout'] and parameter[2][@type='V'] and parameter[3][@type='android.view.MotionEvent']]"
		[Register ("onTouchEvent", "(Landroidx/coordinatorlayout/widget/CoordinatorLayout;Landroid/view/View;Landroid/view/MotionEvent;)Z", "GetOnTouchEvent_Landroidx_coordinatorlayout_widget_CoordinatorLayout_Landroid_view_View_Landroid_view_MotionEvent_Handler")]
		public override unsafe bool OnTouchEvent (global::AndroidX.CoordinatorLayout.Widget.CoordinatorLayout parent, global::Java.Lang.Object child, global::Android.Views.MotionEvent e)
		{
			const string __id = "onTouchEvent.(Landroidx/coordinatorlayout/widget/CoordinatorLayout;Landroid/view/View;Landroid/view/MotionEvent;)Z";
			IntPtr native_child = JNIEnv.ToLocalJniHandle (child);
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [3];
				__args [0] = new JniArgumentValue ((parent == null) ? IntPtr.Zero : ((global::Java.Lang.Object) parent).Handle);
				__args [1] = new JniArgumentValue (native_child);
				__args [2] = new JniArgumentValue ((e == null) ? IntPtr.Zero : ((global::Java.Lang.Object) e).Handle);
				var __rm = _members.InstanceMethods.InvokeVirtualBooleanMethod (__id, this, __args);
				return __rm;
			} finally {
				JNIEnv.DeleteLocalRef (native_child);
				global::System.GC.KeepAlive (parent);
				global::System.GC.KeepAlive (child);
				global::System.GC.KeepAlive (e);
			}
		}

		static Delegate? cb_setCoplanarSiblingViewId_I;
#pragma warning disable 0169
		static Delegate GetSetCoplanarSiblingViewId_IHandler ()
		{
			if (cb_setCoplanarSiblingViewId_I == null)
				cb_setCoplanarSiblingViewId_I = JNINativeWrapper.CreateDelegate (new _JniMarshal_PPI_V (n_SetCoplanarSiblingViewId_I));
			return cb_setCoplanarSiblingViewId_I;
		}

		static void n_SetCoplanarSiblingViewId_I (IntPtr jnienv, IntPtr native__this, int coplanarSiblingViewId)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			__this.SetCoplanarSiblingViewId (coplanarSiblingViewId);
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='setCoplanarSiblingViewId' and count(parameter)=1 and parameter[1][@type='int']]"
		[Register ("setCoplanarSiblingViewId", "(I)V", "GetSetCoplanarSiblingViewId_IHandler")]
		public virtual unsafe void SetCoplanarSiblingViewId (int coplanarSiblingViewId)
		{
			const string __id = "setCoplanarSiblingViewId.(I)V";
			try {
				JniArgumentValue* __args = stackalloc JniArgumentValue [1];
				__args [0] = new JniArgumentValue (coplanarSiblingViewId);
				_members.InstanceMethods.InvokeVirtualVoidMethod (__id, this, __args);
			} finally {
			}
		}

		static Delegate? cb_shouldSkipSmoothAnimation;
#pragma warning disable 0169
		static Delegate GetShouldSkipSmoothAnimationHandler ()
		{
			if (cb_shouldSkipSmoothAnimation == null)
				cb_shouldSkipSmoothAnimation = JNINativeWrapper.CreateDelegate (new _JniMarshal_PP_Z (n_ShouldSkipSmoothAnimation));
			return cb_shouldSkipSmoothAnimation;
		}

		static bool n_ShouldSkipSmoothAnimation (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Google.Android.Material.SideSheet.SideSheetBehavior> (jnienv, native__this, JniHandleOwnership.DoNotTransfer)!;
			return __this.ShouldSkipSmoothAnimation ();
		}
#pragma warning restore 0169

		// Metadata.xml XPath method reference: path="/api/package[@name='com.google.android.material.sidesheet']/class[@name='SideSheetBehavior']/method[@name='shouldSkipSmoothAnimation' and count(parameter)=0]"
		[Register ("shouldSkipSmoothAnimation", "()Z", "GetShouldSkipSmoothAnimationHandler")]
		public virtual unsafe bool ShouldSkipSmoothAnimation ()
		{
			const string __id = "shouldSkipSmoothAnimation.()Z";
			try {
				var __rm = _members.InstanceMethods.InvokeVirtualBooleanMethod (__id, this, null);
				return __rm;
			} finally {
			}
		}

        /*
		// This method is explicitly implemented as a member of an instantiated Google.Android.Material.SideSheet.ISheet
		void global::Google.Android.Material.SideSheet.ISheet.AddCallback (global::Java.Lang.Object? p0)
		{
			AddCallback (global::Java.Interop.JavaObjectExtensions.JavaCast<global::Google.Android.Material.SideSheet.SideSheetCallback>(p0)!);
		}

		// This method is explicitly implemented as a member of an instantiated Google.Android.Material.SideSheet.ISheet
		void global::Google.Android.Material.SideSheet.ISheet.RemoveCallback (global::Java.Lang.Object? p0)
		{
			RemoveCallback (global::Java.Interop.JavaObjectExtensions.JavaCast<global::Google.Android.Material.SideSheet.SideSheetCallback>(p0)!);
		}
        */
        
	}
}
